# -*- coding: utf-8 -*-
"""Tuple_Sorting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jxYM_pAnm_nbwuOdDLLnYgW9PLYbwJoe
"""

#Python Program for Sorting non-empty tuples

def last(n):
    return n[-1] 

def sort(tuples):
    return sorted(tuples, key=last)
 #Sample 
a=[(5, 7), (1, 1), (3, 5), (8, 4), (2, 3)]
print("Sorted:")
print(sort(a))

